-- QUAN LY VE XE

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

-- 1. Tao user ten la BAITHI gom co 4 table XE, TUYEN, KHACH, VEXE.
-- Tao khoa chinh, khoa ngoai cho cac table do
CREATE TABLE BTKHDL1.XE(
    MAXE        VARCHAR2(3),
    BIENKS      VARCHAR2(10),
    MATUYEN     VARCHAR2(4),
    SOGHET1     NUMBER,
    SOGHET2     NUMBER,
    
    CONSTRAINT PK_XE PRIMARY KEY(MAXE)
);

CREATE TABLE BTKHDL1.TUYEN(
    MATUYEN     VARCHAR2(4),
    BENDAU      VARCHAR2(5),
    BENCUOI     VARCHAR2(5),
    GIATUYEN    NUMBER,
    NGXB        DATE,
    TGDK        NUMBER,
    
    CONSTRAINT PK_TUYEN PRIMARY KEY(MATUYEN)
);

CREATE TABLE BTKHDL1.KHACH(
    MAHK        VARCHAR2(4),
    HOTEN       NVARCHAR2(50),
    GIOITINH    NVARCHAR2(10),
    CMND        VARCHAR2(15),
    
    CONSTRAINT PK_KHACH PRIMARY KEY(MAHK)
);

CREATE TABLE BTKHDL1.VEXE(
    MATUYEN     VARCHAR2(4),
    MAHK        VARCHAR2(4),
    NGMUA       DATE,
    GIAVE       NUMBER,
    
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN, MAHK, NGMUA)
);

-- TAO KHOA NGOAI
ALTER TABLE BTKHDL1.XE
ADD CONSTRAINT FK_XE_MATUYEN FOREIGN KEY(MATUYEN) 
REFERENCES BTKHDL1.TUYEN(MATUYEN);

ALTER TABLE BTKHDL1.VEXE
ADD CONSTRAINT FK_VEXE_MATUYEN FOREIGN KEY(MATUYEN) REFERENCES BTKHDL1.TUYEN(MATUYEN);
ALTER TABLE BTKHDL1.VEXE
ADD CONSTRAINT FK_VEXE_MAHK FOREIGN KEY(MAHK) REFERENCES BTKHDL1.KHACH(MAHK);

-- cau 2 Nhap du lieu cho 4 table nhu de bai

-- DISABLE KHOA NGOAI
ALTER TABLE BTKHDL1.XE DISABLE CONSTRAINT FK_XE_MATUYEN;
ALTER TABLE BTKHDL1.VEXE DISABLE CONSTRAINT FK_VEXE_MATUYEN;
ALTER TABLE BTKHDL1.VEXE DISABLE CONSTRAINT FK_VEXE_MAHK;

--INSERT VALUES INTO TABLE XE--
INSERT INTO BTKHDL1.XE VALUES('X01', '52LD-4393', 'T11A', 20, 20);
INSERT INTO BTKHDL1.XE VALUES('X02', '59LD-7247', 'T32D', 36, 36);
INSERT INTO BTKHDL1.XE VALUES('X03', '55LD-6850', 'T06F', 15, 15);

--INSERT VALUES INTO TABLE TUYEN--
INSERT INTO BTKHDL1.TUYEN VALUES
('T11A', 'SG', 'DL', 210000, '26/12/2016', 6);
INSERT INTO BTKHDL1.TUYEN VALUES
('T32D', 'PT', 'SG', 120000, '30/12/2016', 4);
INSERT INTO BTKHDL1.TUYEN VALUES
('T06F', 'NT', 'DNG', 225000, '02/01/2017', 7);

--INSERT VALUES INTO TABLE KHACH--
INSERT INTO BTKHDL1.KHACH VALUES('KH01', 'Lam Van Ben', 'Nam', '655615896');
INSERT INTO BTKHDL1.KHACH VALUES('KH02', 'Duong Thi Luc', 'Nu', '275648642');
INSERT INTO BTKHDL1.KHACH VALUES('KH03', 'Hoang Thanh Tung', 'Nam', '456889143');

--INSERT VALUES INTO TABLE VEXE--
INSERT INTO BTKHDL1.VEXE VALUES('T11A', 'KH01', '20/12/2016', 210000);
INSERT INTO BTKHDL1.VEXE VALUES('T32D', 'KH02', '25/12/2016', 144000);
INSERT INTO BTKHDL1.VEXE VALUES('T06F', 'KH03', '30/12/2016', 270000);

-- ENABLE KHOA NGOAI
ALTER TABLE BTKHDL1.XE ENABLE CONSTRAINT FK_XE_MATUYEN;
ALTER TABLE BTKHDL1.VEXE ENABLE CONSTRAINT FK_VEXE_MATUYEN;
ALTER TABLE BTKHDL1.VEXE ENABLE CONSTRAINT FK_VEXE_MAHK;

SELECT * FROM KHACH;
SELECT * FROM TUYEN;
SELECT * FROM XE;
SELECT * FROM VEXE;

-- 3. Hien thuc rang buoc toan ven sau:
-- Cac tuyen xe co Thoi gian du kien lon hon 5 tieng luon co gia tuyen lon hon 200.000.
ALTER TABLE BTKHDL1.TUYEN 
ADD CONSTRAINT CHECK_GIATUYEN CHECK((TGDK > 5 AND GIATUYEN > 200.000) OR TGDK <= 5);

-- 4. Hien thuc rang buoc toan ven sau: Tuyen xe co ngay xuat ben tu ngay 29/12/2016
-- den ngay 05/01/2017 se co gia ve tang 20%.


-- 5. Tim tat ca cac ve xe mua trong thang 12, sap xep ket qua giam dan theo gia ve.
SELECT *
FROM BTKHDL1.VEXE
WHERE EXTRACT(MONTH FROM (NGMUA)) = 12
ORDER BY GIAVE DESC;

-- 6. Tim tuyen xe co so ve xe it nhat trong nam 2016
SELECT DISTINCT MATUYEN
FROM BTKHDL1.VEXE
WHERE EXTRACT(YEAR FROM(VEXE.NGMUA))=2016
GROUP BY MATUYEN
HAVING COUNT(MATUYEN) <= ALL (
                                SELECT COUNT(MATUYEN)
                                FROM BTKHDL1.VEXE
                                WHERE EXTRACT(YEAR FROM(VEXE.NGMUA))=2016
                                GROUP BY MATUYEN
                             );
    

-- 7. Tim tuyen xe co ca hanh khach nam va hanh khach nu mua ve.
SELECT BTKHDL1.TUYEN.MATUYEN
FROM BTKHDL1.TUYEN, BTKHDL1.KHACH, BTKHDL1.VEXE
WHERE VEXE.MAHK = KHACH.MAHK AND VEXE.MATUYEN = TUYEN.MATUYEN
AND GIOITINH='Nam'
INTERSECT
SELECT BTKHDL1.TUYEN.MATUYEN
FROM BTKHDL1.TUYEN, BTKHDL1.KHACH, BTKHDL1.VEXE
WHERE VEXE.MAHK = KHACH.MAHK AND VEXE.MATUYEN = TUYEN.MATUYEN
AND GIOITINH='Nu';

--  8. Tim hanh khach nu da tung mua ve tat ca cac tuyen xe.
SELECT *
FROM BTKHDL1.KHACH KHACH
WHERE GIOITINH = 'Nu'
    AND NOT EXISTS (
        SELECT *
        FROM BTKHDL1.TUYEN TUYEN 
        WHERE NOT EXISTS (
            SELECT *
            FROM BTKHDL1.VEXE VEXE
            WHERE VEXE.MATUYEN = TUYEN.MATUYEN
            AND VEXE.MAHK = KHACH.MAHK
        )
    );

