ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

--1. Tao user ten BAITHI gom co 4 table USER, CHANNEL, VIDEO, SHARE. Tao khoa chinh,
--khoa ngoai cho cac table do.
CREATE TABLE BTKHDL2.USER_NEW(
    U_ID        VARCHAR2(10),
    USERNAME    VARCHAR2(30),
    PASS        VARCHAR2(30),
    REGDAY      DATE,
    NATIONALITY VARCHAR2(50),
    
    CONSTRAINT PK_USER_NEW PRIMARY KEY(U_ID)
);

CREATE TABLE BTKHDL2.CHANNEL(
    CHANNELID  VARCHAR2(10),
    CNAME      VARCHAR2(20),
    SUBSCRIBES NUMBER,
    OWNER_NEW  VARCHAR2(10),
    CREATED    DATE,
    
    CONSTRAINT PK_CHANNEL PRIMARY KEY(CHANNELID)
);

CREATE TABLE BTKHDL2.VIDEO(
    VIDEOID      VARCHAR2(10),
    TITLE        NVARCHAR2(60),
    DURATION_NEW NUMBER,
    AGE          NUMBER,
    
    CONSTRAINT PK_VIDEO PRIMARY KEY(VIDEOID)
);

CREATE TABLE BTKHDL2.SHARE_NEW(
    VIDEOID   VARCHAR2(10),
    CHANNELID VARCHAR2(10),
    
    CONSTRAINT PK_SHARE_NEW PRIMARY KEY (VIDEOID, CHANNELID)
);

ALTER TABLE BTKHDL2.CHANNEL
ADD CONSTRAINT FK_CHANNEL_OWNER_NEW FOREIGN KEY(OWNER_NEW)
REFERENCES BTKHDL2.USER_NEW(U_ID);

ALTER TABLE BTKHDL2.SHARE_NEW
ADD CONSTRAINT FK_SHARE_NEW_VIDEOID FOREIGN KEY(VIDEOID)
REFERENCES BTKHDL2.VIDEO(VIDEOID);

ALTER TABLE BTKHDL2.SHARE_NEW
ADD CONSTRAINT FK_SHARE_NEW_CHANNELID FOREIGN KEY(CHANNELID)
REFERENCES BTKHDL2.CHANNEL(CHANNELID);

--2. Nhap du lieu cho 4 table nhu de bai.
-- DISABLE KHOA NGOAI
ALTER TABLE BTKHDL2.CHANNEL   DISABLE CONSTRAINT FK_CHANNEL_OWNER_NEW;
ALTER TABLE BTKHDL2.SHARE_NEW DISABLE CONSTRAINT FK_SHARE_NEW_VIDEOID;
ALTER TABLE BTKHDL2.SHARE_NEW DISABLE CONSTRAINT FK_SHARE_NEW_CHANNELID;

-- insert values into USER_NEW
SET DEFINE OFF;
INSERT INTO BTKHDL2.USER_NEW VALUES('1', 'faptv', '123456abc', '01/01/2014', 'Viet Nam');
INSERT INTO BTKHDL2.USER_NEW VALUES('2', 'kemxoitv', '@147869iii', '05/06/2015', 'Campuchia');
INSERT INTO BTKHDL2.USER_NEW VALUES('3', 'openshare', 'qwertyuiop', '12/05/2009', 'Viet Nam');

-- insert values into CHANNEL
SET DEFINE OFF;
INSERT INTO BTKHDL2.CHANNEL VALUES('C120', 'FAP TV', 2343, 1, '02/01/2014');
INSERT INTO BTKHDL2.CHANNEL VALUES('C905', 'Kem xoi TV', 1032, 2, '09/07/2015');
INSERT INTO BTKHDL2.CHANNEL VALUES('C357', 'OpenShare Cafe', 5064, 3, '10/12/2010');

-- insert values into VIDEO
SET DEFINE OFF;
INSERT INTO BTKHDL2.VIDEO VALUES('V100229', 'FAPtv Com Nguoi Tap 41 - Dot Nhap', 469, 18);
INSERT INTO BTKHDL2.VIDEO VALUES('V211002', 'Kem xoi: Tap 31 -  May Kool tinh yeu cua anh', 312, 16);
INSERT INTO BTKHDL2.VIDEO VALUES('V400002', 'Noi tinh yeu ket thuc - Hoang Tuan', 378, 0);

-- insert values into SHARE
SET DEFINE OFF;
INSERT INTO BTKHDL2.SHARE_NEW VALUES('V100229', 'C905');
INSERT INTO BTKHDL2.SHARE_NEW VALUES('V211002', 'C120');
INSERT INTO BTKHDL2.SHARE_NEW VALUES('V400002', 'C357');

-- ENABLE KHOA NGOAI
ALTER TABLE BTKHDL2.CHANNEL   ENABLE CONSTRAINT FK_CHANNEL_OWNER_NEW;
ALTER TABLE BTKHDL2.SHARE_NEW ENABLE CONSTRAINT FK_SHARE_NEW_VIDEOID;
ALTER TABLE BTKHDL2.SHARE_NEW ENABLE CONSTRAINT FK_SHARE_NEW_CHANNELID;


SELECT * FROM BTKHDL2.USER_NEW;
SELECT * FROM BTKHDL2.CHANNEL;
SELECT * FROM BTKHDL2.VIDEO;
SELECT * FROM BTKHDL2.SHARE_NEW;

--3. Hien thuc rang buoc toan ven sau: Ngay dang ky duoc mac dinh la ngay hien tai.

--4. Hien thuc rang buoc toan ven sau: Ngay tao kenh luon lon hon hoac bang ngay dang ky cua
--nguoi dung so huu kenh do.

--5. Tim tat ca cac video co gioi han do tuoi tu 16 tro len.
SELECT *
FROM BTKHDL2.VIDEO
WHERE AGE >= 16

--6. Tìm kênh có số người theo dõi nhiều nhất.
SELECT *
FROM BTKHDL2.CHANNEL
WHERE SUBSCRIBES >= ALL(
                            SELECT SUBSCRIBES
                            FROM BTKHDL2.CHANNEL     
                       );
                               
--7. Voi moi video co gioi han do tuoi la 18, thong ke so kenh da chia se.
SELECT VIDEO.VIDEOID, COUNT(CHANNELID) AS SHARED_CHANNELS
FROM BTKHDL2.VIDEO VIDEO
JOIN BTKHDL2.SHARE_NEW SHARE_
ON VIDEO.VIDEOID = SHARE_.VIDEOID
WHERE AGE > 18
GROUP BY VIDEO.VIDEOID;

--8. Tim video duoc tat ca cac kenh chia se.
SELECT *
FROM BTKHDL2.VIDEO VIDEO
WHERE NOT EXISTS(
    SELECT *
    FROM BTKHDL2.CHANNEL CHANNEL
    WHERE NOT EXISTS(
        SELECT *
        FROM BTKHDL2.SHARE_NEW SHARE_
        WHERE     SHARE_.VIDEOID = VIDEO.VIDEOID
            AND SHARE_.CHANNELID = CHANNEL.CHANNELID
    )
);