CREATE OR REPLACE TRIGGER THEM_SUA_CB
AFTER INSERT OR UPDATE ON BaiTapKHDL3.CHUYENBAY
FOR EACH ROW
DECLARE
    BATDAU DATE;
    NGTL1 DATE;
BEGIN 
    BATDAU := :NEW.BATDAU;
    SELECT NGTL INTO NGTL1 FROM BaiTapKHDL3.HANGHANGKHONG WHERE MAHANG = :NEW.MAHANG;
    IF (BATDAU<=NGTL1) THEN
        ROLLBACK;
    END IF;
END;

CREATE OR REPLACE TRIGGER SUA_HHK
AFTER UPDATE ON BaiTapKHDL3.HANGHANGKHONG
FOR EACH ROW
DECLARE
    BATDAU1 DATE;
    NGTL DATE;
BEGIN 
    NGTL := :NEW.NGTL;
    SELECT BATDAU INTO BATDAU1 FROM BaiTapKHDL3.CHUYENBAY WHERE MAHANG = :NEW.MAHANG;
    IF (BATDAU1<=NGTL) THEN
        ROLLBACK;
    END IF;
END;

