--CAU1--
CREATE TABLE BTKHDL1.HANGHANGKHONG
(MAHANG VARCHAR2(2),
TENHANG VARCHAR (50),
NGTL DATE,
DUONGBAY NUMBER,
CONSTRAINT PK_HANGHANGKHONG PRIMARY KEY (MAHANG)); 

CREATE TABLE BTKHDL1.CHUYENBAY
(MACB VARCHAR2(5),
MAHANG VARCHAR2(2),
XUATPHAT NVARCHAR2 (20),
DIEMDEN NVARCHAR2 (20),
BATDAU DATE,
TGBAY FLOAT,

CONSTRAINT PK_CHUYENBAY PRIMARY KEY (MACB),
CONSTRAINT FK_HHK_CB FOREIGN KEY (MAHANG) REFERENCES HANGHANGKHONG(MAHANG))
; 

CREATE TABLE BTKHDL1.NHANVIEN
(MANV VARCHAR2(4),
HOTEN NVARCHAR2(20),
GIOITINH NVARCHAR2 (3),
NGSINH DATE,
NGVL DATE,
CHUYENMON NVARCHAR2(20),

CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV));

CREATE TABLE BTKHDL1.PHANCONG
(MACB VARCHAR2(5),
MANV VARCHAR2(4),
NHIEMVU NVARCHAR2 (30),

CONSTRAINT FK_PC_CB FOREIGN KEY (MACB) REFERENCES CHUYENBAY(MACB),
CONSTRAINT FK_PC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV))
; 

--CAU2--
INSERT INTO HANGHANGKHONG VALUES ('VN','Vietnam Airlines',TO_DATE('15/01/1956','dd/mm/yyyy'),52);
INSERT INTO HANGHANGKHONG VALUES ('VJ', 'Vietjet Air', TO_DATE('25/12/2011','dd/mm/yyyy'),33);
INSERT INTO HANGHANGKHONG VALUES ('BL', 'Jetstar Pacific Airlines', TO_DATE('01/12/1990','dd/mm/yyyy'), 13);

SELECT * FROM HANGHANGKHONG;

ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH24:MI:SS';

--INSERT INTO CHUYENBAY VALUES ('VN550','VN','TP.HCM','Singapore',TIMESTAMP'2015-12-20 13:15:00',2);
INSERT INTO CHUYENBAY VALUES ('VN550','VN','TP.HCM','Singapore',TO_DATE('20-12-2015 13:15:00','dd/mm/yyyy hh24:mi:ss'),2);
INSERT INTO CHUYENBAY VALUES ('VJ331', 'VJ', 'Da Nang', 'Vinh', TO_DATE('28/12/2015 22:30','dd/mm/yyyy hh24:mi:ss'),1);
INSERT INTO CHUYENBAY VALUES ('BL696','BL', 'TP.HCM', '?a Lat', TO_DATE('24/12/2015 06:00','dd/mm/yyyy hh24:mi:ss'),0.5);

SELECT * FROM CHUYENBAY;



INSERT INTO NHANVIEN VALUES ('NV01', 'Lam Van Ben', 'Nam', TO_DATE('10/09/1978','dd/mm/yyyy'), TO_DATE('05/06/2000','dd/mm/yyyy'), 'Phi cong');
INSERT INTO NHANVIEN VALUES ('NV02', 'Duong Thi Luc', 'Nu', TO_DATE('22/03/1989','dd/mm/yyyy'), TO_DATE('12/11/2013','dd/mm/yyyy'), 'Tiep vien');
INSERT INTO NHANVIEN VALUES ('NV03', 'Hoang Thanh Tung', 'Nam', TO_DATE('29/07/1983','dd/mm/yyyy'), TO_DATE('11/04/2007','dd/mm/yyyy'), 'Tiep vien');

SELECT * FROM NHANVIEN;

INSERT INTO PHANCONG VALUES ('VN550', 'NV01', 'Co truong');
INSERT INTO PHANCONG VALUES ('VN550','NV02','Tiep vien');
INSERT INTO PHANCONG VALUES ('BL696','NV03', 'Tiep vien truong');

SELECT * FROM PHANCONG;

--CAU3--
--RBTYV: Chuyen mon =(Phi cong, Tiep Vien)--
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_CHUYENMON 
CHECK (CHUYENMON IN ('Phi cong','Tiep vien'));

--CAU4--
--RBTV: BATDAU >NGTL--
CREATE OR REPLACE TRIGGER CAU4_CB
BEFORE INSERT OR UPDATE ON BTKHDL1.CHUYENBAY
FOR EACH ROW
DECLARE
  N_NGTL DATE;
BEGIN
  SELECT BTKHDL1.CHUYENBAY INTO N_NGTL
  FROM   BTKHDL1.HANGHANGKHONG 
  WHERE BTKHDL1.HANGHANGKHONG.MAHANG = :NEW.MAHANG;
  
  IF :NEW.BATDAU <= N_NGTL THEN
    RAISE_APPLICATION_ERROR (-20100,'LOI')
  END IF;
END;

CREATE OR REPLACE TRIGGER CAU4_HANGKHONG
BEFORE INSERT OR UPDATE ON BTKHDL1.HANGHANGKHONG
FOR EACH ROW
DECLARE
  N_NGBD DATE;
BEGIN
  SELECT BTKHDL1.BATDAU INTO N_NGBD
  FROM  BTKHDL1.BATDAU 
  WHERE BTKHDL1.HANGHANGKHONG.MACB = :NEW.MACB;
  
  IF N_NGBD <= :NEW.NGTL THEN
    RAISE_APPLICATION_ERROR (-20100,'LOI')
  END IF;
END;
--CAU5--
--Tim: MONTH(NGSINH) =7

SELECT * 
FROM NHANVIEN
WHERE EXTRACT(MONTH FROM NGSINH)=7;

--CAU6--
--Tim: CHUYEN BAY co so nhan vien NHIEU NHAT

SELECT *
FROM CHUYENBAY CB
WHERE CB.MACB=
        (SELECT MACB
        FROM PHANCONG
        GROUP BY MACB
        HAVING COUNT(MANV) >= ALL (SELECT COUNT(PC1.MANV) 
                                    FROM PHANCONG PC1
                                    GROUP BY PC1.MACB));
                           
--SELECT MACB,COUNT(MANV) AS SO_NV
--FROM PHANCONG
--GROUP BY MACB
--ORDER BY COUNT(MANV) DESC
--FETCH FIRST 1 ROW ONLY;

--CAU7--
-- voi moi HANGHANGKHONG, thong ke XUATPHAT="Da Nang" AND COUNT(MANV) <2

--insert de check--
INSERT INTO PHANCONG VALUES ('VJ331', 'NV01', 'Co truong');


SELECT *
FROM CHUYENBAY CB
WHERE XUATPHAT ='Da Nang' AND CB.MACB IN (SELECT PC.MACB
                                        FROM PHANCONG PC
                                        GROUP BY PC.MACB
                                        HAVING COUNT(MANV)<2);
--CAU8--
--NHANVIEN tham gia tat ca CHUYENBAY
 SELECT * FROM PHANCONG;

--them data de check--
INSERT INTO PHANCONG VALUES ('BL696', 'NV01', 'Co truong');


SELECT *
FROM NHANVIEN NV
WHERE NOT EXISTS (
    SELECT *
    FROM CHUYENBAY CB
    WHERE NOT EXISTS (
        SELECT * 
        FROM PHANCONG PC
        WHERE PC.MACB =CB.MACB AND
                PC.MANV=NV.MANV));