/*Cau_1*/
create table BaiTapKHDL3.HANGHANGKHONG
(
    MAHANG VARCHAR2(2) CONSTRAINT PK_HHKID PRIMARY KEY,
    TENHANG VARCHAR2(40),
    NGTL DATE,
    DUONGBAY NUMBER
)
CREATE TABLE BaiTapKHDL3.CHUYENBAY
(
    MACB VARCHAR2(5) CONSTRAINT PK_CB PRIMARY KEY,
    MAHANG VARCHAR2(2),
    XUATPHAT VARCHAR(20),
    DIEMDEN VARCHAR(20),
    BATDAU DATE,
    TGBAY NUMBER
)
CREATE TABLE BaiTapKHDL3.NHANVIEN
(
    MANV VARCHAR2(4) CONSTRAINT PK_NV PRIMARY KEY,
    HOTEN VARCHAR2(20),
    GIOITINH VARCHAR2(3),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR(10)
)
CREATE TABLE BaiTapKHDL3.PHANCONG
(
    MACB VARCHAR2(5),
    MANV VARCHAR2(4),
    NHIEMVU VARCHAR(20),
    CONSTRAINT PK_PC PRIMARY KEY (MACB,MANV)
)
drop table BaiTapKHDL3.CHUYENBAY
/*Cau_2*/
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapKHDL3.HANGHANGKHONG VALUES
('VN','Vietnam Airlines','15/01/1956',52);
INSERT INTO BaiTapKHDL3.HANGHANGKHONG VALUES
('VJ','Vietjet Air','25/12/2011',33);
INSERT INTO BaiTapKHDL3.HANGHANGKHONG VALUES
('BL','Jetstar Pacific Airlines','01/12/1990',13);

INSERT INTO BaiTapKHDL3.CHUYENBAY VALUES
('VN550','VN','TP.HCM','Singapore','20/12/2015 13:15:00',2);
INSERT INTO BaiTapKHDL3.CHUYENBAY VALUES
('VJ331','VJ','Da Nang','Vinh','28/12/2015 23:30:00',1);
INSERT INTO BaiTapKHDL3.CHUYENBAY VALUES
('BL696','BL','TP.HCM','Da Lat','24/12/2015 06:00:00', 0.5);

INSERT INTO BaiTapKHDL3.NHANVIEN VALUES
('NV01','Lam Van Ben','Nam','10/09/1978','05/06/2000','Phi cong');
INSERT INTO BaiTapKHDL3.NHANVIEN VALUES
('NV02','Duong Thi Luc','Nu','22/03/1989','12/11/2013','Tiep vien');
INSERT INTO BaiTapKHDL3.NHANVIEN VALUES
('NV03','Hoang Thanh Tung','Nam','29/07/1983','11/04/2007','Tiep vien');

INSERT INTO BaiTapKHDL3.PHANCONG VALUES 
('VN550', 'NV01', 'Co truong');
INSERT INTO BaiTapKHDL3.PHANCONG VALUES 
('VN550', 'NV02', 'Tiep vien');
INSERT INTO BaiTapKHDL3.PHANCONG VALUES 
('BL696', 'NV03', 'Tiep vien truong');

/*Cau_3*/
ALTER TABLE BaiTapKHDL3.NHANVIEN
ADD CONSTRAINT CK_CM CHECK(CHUYENMON = 'Phi Cong' OR CHUYENMON = 'Tiep Vien')
ENABLE NOVALIDATE;

/*Cau_5*/
SELECT * 
FROM BaiTapKHDL3.NHANVIEN
WHERE EXTRACT(MONTH from NGSINH)=7

/*Cau_6*/
SELECT BaiTapKHDL3.CHUYENBAY.MACB, COUNT(*) as SONV
FROM BaiTapKHDL3.CHUYENBAY JOIN BaiTapKHDL3.PHANCONG 
ON BaiTapKHDL3.CHUYENBAY.MACB = BaiTapKHDL3.PHANCONG.MACB
GROUP BY BaiTapKHDL3.CHUYENBAY.MACB
ORDER BY COUNT(*) DESC
FETCH FIRST 1 ROWS ONLY;

/*Cau_7*/

SELECT BaiTapKHDL3.CHUYENBAY.MAHANG, COUNT(*)
FROM BaiTapKHDL3.CHUYENBAY JOIN BaiTapKHDL3.HANGHANGKHONG 
ON BaiTapKHDL3.CHUYENBAY.MAHANG = BaiTapKHDL3.HANGHANGKHONG.MAHANG
GROUP BY BaiTapKHDL3.CHUYENBAY.MAHANG


/*Cau_8*/
SELECT *
FROM BaiTapKHDL3.NHANVIEN
WHERE NOT EXISTS (SELECT *
                  FROM BaiTapKHDL3.CHUYENBAY
                  WHERE NOT EXISTS (SELECT *
                                    FROM BaiTapKHDL3.PHANCONG
                                    WHERE BaiTapKHDL3.NHANVIEN.MANV = BaiTapKHDL3.PHANCONG.MANV
                                    AND BaiTapKHDL3.CHUYENBAY.MACB = BaiTapKHDL3.PHANCONG.MACB
                                    )
                  )

