/*Cau_1*/
CREATE TABLE BaiTapKHDL1.XE 
(
    MAXE VARCHAR2(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(10),
    MATUYEN VARCHAR(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
)

CREATE TABLE BaiTapKHDL1.TUYEN
(
    MATUYEN VARCHAR(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR(3) NOT NULL,
    BENCUOI VARCHAR(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)

CREATE TABLE BaiTapKHDL1.KHACH
(
    MAHK VARCHAR(4) CONSTRAINT PK_KHACH PRIMARY KEY,
    HOTEN VARCHAR(30),
    GIOITINH VARCHAR(3),
    CMND VARCHAR(12)
)

CREATE TABLE BaiTapKHDL1.VEXE
(
    MATUYEN VARCHAR(4),
    MAHK VARCHAR(4),
    NGMUA DATE,
    GIAVE DECIMAL,
    CONSTRAINT PK_VEXE PRIMARY KEY (MATUYEN,MAHK,NGMUA)
)

/*Cau_2*/
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapKHDL1.XE VALUES
('X01','52LD-4393','T11A',20,20);
INSERT INTO BaiTapKHDL1.XE VALUES
('X02','59LD-7247','T32D',36,36);
INSERT INTO BaiTapKHDL1.XE VALUES
('X03','52LD-6850','T06F',15,15);

INSERT INTO BaiTapKHDL1.TUYEN VALUES
('T11A','SG','DL',210000,'26/12/2016',6);
INSERT INTO BaiTapKHDL1.TUYEN VALUES
('T32D','PT','SG',120000,'30/12/2016',4);
INSERT INTO BaiTapKHDL1.TUYEN VALUES
('T06F','NT','DNG',225000,'02/01/2017',7);

INSERT INTO BaiTapKHDL1.KHACH VALUES
('KH01','Lam Van Ben','Nam','655615896');
INSERT INTO BaiTapKHDL1.KHACH VALUES
('KH02','Duong Thi Luc','Nu','275648642');
INSERT INTO BaiTapKHDL1.KHACH VALUES
('KH03','Hoang Thanh Tung','Nam','456889143');

INSERT INTO BaiTapKHDL1.VEXE VALUES
('T11A','KH01',TO_DATE('20/12/2016','DD/MM/YYYY'),210000);
INSERT INTO BaiTapKHDL1.VEXE VALUES
('T32D','KH02',TO_DATE('25/12/2016','DD/MM/YYYY'),144000);
INSERT INTO BaiTapKHDL1.VEXE VALUES
('T06F','KH03',TO_DATE('30/12/2016','DD/MM/YYYY'),270000);


/*Cau_3*/
ALTER TABLE BaiTapKHDL1.TUYEN
ADD CONSTRAINT CK_TGDK CHECK(TGDK>5 AND GIATUYEN>200000)
ENABLE NOVALIDATE;

/*Cau_5*/
SELECT *
FROM BaiTapKHDL1.VEXE
WHERE EXTRACT(MONTH FROM (NGMUA)) = 12
ORDER BY GIAVE DESC;

/*Cau_6*/
SELECT MATUYEN
from baitapkhdl1.VEXE
where EXTRACT(year from ngmua)=2016
group by matuyen
having count (matuyen) <= all (
                                SELECT count(matuyen)
                                from baitapkhdl1.vexe
                                where EXTRACT(year from ngmua)=2016
                                group by matuyen
                                );
/*Cau_7*/
SELECT BaiTapKHDL1.TUYEN.MATUYEN
FROM baitapkhdl1.tuyen, baitapkhdl1.khach, baitapkhdl1.vexe
where VEXE.MAHK = KHACH.MAHK and VEXE.MATUYEN=TUYEN.MATUYEN
AND GIOITINH = 'Nam'
INTERSECT
SELECT BaiTapKHDL1.TUYEN.MATUYEN
FROM baitapkhdl1.tuyen, baitapkhdl1.khach, baitapkhdl1.vexe
where VEXE.MAHK = KHACH.MAHK and VEXE.MATUYEN=TUYEN.MATUYEN
AND GIOITINH = 'Nu'

/*Cau_8*/
SELECT *
FROM BaiTapKHDL1.KHACH
WHERE GIOITINH = 'Nu'
AND NOT EXISTS (SELECT *
                FROM BaiTapKHDL1.TUYEN
                WHERE NOT EXISTS (SELECT *
                                FROM BaiTapKHDL1.VEXE
                                WHERE BaiTapKHDL1.TUYEN.MATUYEN = BaiTapKHDL1.VEXE.MATUYEN
                                AND BaiTapKHDL1.KHACH.MAHK = BaiTapKHDL1.VEXE.MAHK
                                )
                )
