/*Cau_1*/
CREATE TABLE BaiTapKHDL2.USER_NEW
(
    U_ID VARCHAR2(3) CONSTRAINT PK_UID PRIMARY KEY,
    USERNAME VARCHAR2(10),
    PASS VARCHAR(20),
    REGDAY DATE,
    NATIONALITY VARCHAR(20)
)

CREATE TABLE BaiTapKHDL2.CHANNEL
(
    CHANNELID VARCHAR2(4) CONSTRAINT PK_CID PRIMARY KEY,
    CNAME VARCHAR2(20),
    SUBCRIBES NUMBER,
    OWNNER VARCHAR(3),
    CREATED DATE
)

CREATE TABLE BaiTapKHDL2.VIDEO
(
    VIDEOID VARCHAR2(7) CONSTRAINT PK_VIDEO PRIMARY KEY,
    TITLE VARCHAR2(50),
    DURATION NUMBER,
    AGE NUMBER
)

CREATE TABLE BaiTapKHDL2.SHARE_NEW
(
    VIDEOID VARCHAR2(7),
    CHANNELID VARCHAR2(4),
    CONSTRAINT PK_SHARE PRIMARY KEY(VIDEOID,CHANNELID)
)

/*Cau_2*/
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapKHDL2.USER_NEW VALUES
('001','faptv','123456abc','01/01/2014','Viet Nam');
INSERT INTO BaiTapKHDL2.USER_NEW VALUES
('002','kemxoitv','@147869iii','05/06/2015','Campuchia');
INSERT INTO BaiTapKHDL2.USER_NEW VALUES
('003','openshare','qwertyuiop','12/05/2009','Viet Nam');

INSERT INTO BaiTapKHDL2.CHANNEL VALUES
('C120','FAP TV',2343,'001','02/01/2014');
INSERT INTO BaiTapKHDL2.CHANNEL VALUES
('C905','Kem xoi TV',1032,'002','09/07/2015');
INSERT INTO BaiTapKHDL2.CHANNEL VALUES
('C357','OpenShare Cafe',5064,'003','10/12/2010');

INSERT INTO BaiTapKHDL2.VIDEO VALUES
('V100229','FAPtv Com Nguoi Tap 41 - Dot Nhap',469,18);
INSERT INTO BaiTapKHDL2.VIDEO VALUES
('V211002','Kem xoi: Tap 31 - May Kool tinh yeu cua anh',312,16);
INSERT INTO BaiTapKHDL2.VIDEO VALUES
('v400002','Noi tinh yeu ket thuc - Hoang Tuan',378,0);

INSERT INTO BaiTapKHDL2.SHARE_NEW VALUES
('V100229','C905');
INSERT INTO BaiTapKHDL2.SHARE_NEW VALUES
('V211002','C120');
INSERT INTO BaiTapKHDL2.SHARE_NEW VALUES
('v400002','C357');


/*Cau_3*/

/*Cau_5*/
SELECT * 
FROM BaiTapKHDL2.VIDEO
WHERE AGE >= 16

/*Cau_6*/
SELECT *
FROM BaiTapKHDL2.CHANNEL
WHERE SUBCRIBES = (SELECT MAX(SUBCRIBES)
                      FROM BaiTapKHDL2.CHANNEL)
                      
/*Cau_7*/
SELECT COUNT(BaiTapKHDL2.SHARE_NEW.CHANNELID)
FROM BaiTapKHDL2.SHARE_NEW INNER JOIN BaiTapKHDL2.VIDEO 
ON BaiTapKHDL2.SHARE_NEW.VIDEOID = BaiTapKHDL2.VIDEO.VIDEOID
WHERE BaiTapKHDL2.VIDEO.AGE=18

/*Cau_8*/
SELECT *
FROM BaitapKHDL2.CHANNEL
WHERE NOT EXISTS (SELECT * 
                  FROM BaitapKHDL2.VIDEO
                  WHERE NOT EXISTS (SELECT *
                                    FROM BaiTapKHDL2.SHARE_NEW
                                    WHERE BaitapKHDL2.CHANNEL.CHANNELID =  BaiTapKHDL2.SHARE_NEW.CHANNELID
                                    AND BaitapKHDL2.VIDEO.VIDEOID = BaiTapKHDL2.SHARE_NEW.VIDEOID
                                    )
                  )

